version: '3.8'

networks:
    dockerapi-dev:
        driver: bridge

services:
    postgres_image:
        container_name: 'postgres'
        image: postgres:latest
        environment:
            # change this for a "real" app!
            POSTGRES_PASSWORD: '4y7sV96vA9wv46VR'
            POSTGRES_USER: 'postgres_user'
            POSTGES_DB: 'bouldersDb'
            PGDATA: /data/postgres
        restart: always
        volumes:
            - postgres:/data/postgres
        networks:
            - dockerapi-dev
        ports:
            - 5432:5432

volumes:
    postgres:
