name: boulder-api docker

on:
 push:
    branches: [ "main" ]
 pull_request:
    branches: [ "main" ]

jobs:
  build:
      runs-on: ubuntu-latest
      defaults:
           run:
            working-directory: ./src/services/boulders/boulder.api/

      steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
